[package]
name = "malware-analysis-sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
chrono = { version = "0.4.26", features = ["serde"] }
clap = { version = "4.3.21", features = ["derive"] }
env_logger = "0.10.0"
itertools = "0.11.0"
log = "0.4.19"
mongodb = "2.6.0"
rand = "0.8.5"
regex = "1.9.1"
roxmltree = "0.18.0"
serde = "1.0.181"
serde_json = "1.0.104"
sha3 = "0.10.8"
tokio = { version = "1.29.1", features = ["full"] }
uuid = "1.4.1"
yara = { version = "0.20.0", features = ["vendored"] }
